export interface DocEntry {
  type: string;
  auth: string;
  date: string;
  translation: string;
  deadline: string;
  action: string;
}

export interface StepEntry { n: string; t: string; d: string; }
export interface PersonaEntry { t: string; d: string; }
export interface PrivacyPoint { t: string; d: string; }

export interface LangContent {
  dir: "ltr" | "rtl";
  nav_cta: string;
  lang_label: string;
  hero_kicker: string;
  hero_h1_1: string;
  hero_h1_2: string;
  hero_sub: string;
  hero_cta: string;
  hero_meta: string;
  doc_plain: string;
  doc_deadline: string;
  doc_action: string;
  docs: DocEntry[];
  how_label: string;
  how_h: string;
  how_sub: string;
  steps: StepEntry[];
  who_label: string;
  who_h: string;
  who_sub: string;
  personas: PersonaEntry[];
  privacy_label: string;
  privacy_h: string;
  privacy_sub: string;
  privacy_points: PrivacyPoint[];
  waitlist_h: string;
  waitlist_sub: string;
  waitlist_placeholder: string;
  waitlist_cta: string;
  waitlist_joining: string;
  waitlist_ok_t: string;
  waitlist_ok_d: string;
  waitlist_err: string;
  footer_copy: string;
  footer_disclaimer: string;
}

export type Language = "EN" | "DE" | "FR" | "IT" | "SV" | "PL" | "UK" | "RU" | "ES" | "TR" | "RO" | "HU" | "SO" | "FA" | "TI" | "AM" | "SW" | "HA" | "AR" | "ZH";
export type Direction = "A" | "B";

export interface TweakState {
  direction: Direction;
  language: Language;
  accent: boolean;
}

export const TWEAK_DEFAULTS: TweakState = {
  direction: "B",
  language: "EN",
  accent: true,
};

export const CONTENT: Record<Language, LangContent> = {
  EN: {
    dir: "ltr",
    nav_cta: "Join the waitlist",
    lang_label: "Language",
    hero_kicker: "STRUCTURED INFORMATION · NOT LEGAL ADVICE",
    hero_h1_1: "The immigration system,",
    hero_h1_2: "translated.",
    hero_sub: "Upload a document. Understand what it means. Know what to do, and when.",
    hero_cta: "Join the waitlist",
    hero_meta: "No file is stored. Processed and discarded.",
    doc_plain: "Plain language",
    doc_deadline: "Deadline",
    doc_action: "Required action",
    docs: [
      { type: "Permit Notice", auth: "Immigration Authority", date: "Issued 12 April 2026", translation: "Your work permit has been approved. Collect it in person within 30 days.", deadline: "12 May 2026", action: "Book collection appointment" },
      { type: "Appointment Letter", auth: "Biometric Services", date: "Issued 03 April 2026", translation: "You have been scheduled for a biometric appointment. Attendance is mandatory.", deadline: "28 April 2026", action: "Attend in person" },
      { type: "Appeal Decision", auth: "Administrative Court", date: "Issued 21 March 2026", translation: "Your appeal is under review. A written decision will be issued within 60 days.", deadline: "20 May 2026", action: "Await written notice" },
      { type: "Additional Documentation", auth: "Immigration Authority", date: "Issued 08 April 2026", translation: "Further documents are required. Submit the listed items within 14 days or your case is suspended.", deadline: "22 April 2026", action: "Submit 3 documents" },
    ],
    how_label: "Process",
    how_h: "How it works",
    how_sub: "Three steps, no jargon.",
    steps: [
      { n: "01", t: "Upload your document", d: "Any official letter or notice from an immigration authority." },
      { n: "02", t: "We explain it", d: "Plain language summary, dates, and what is being asked of you." },
      { n: "03", t: "You know what to do", d: "Clear next steps and deadlines, in the correct order." },
    ],
    who_label: "Who it's for",
    who_h: "Built for people inside the system.",
    who_sub: "Individual immigrants, the NGOs supporting them, and lawyers advising them.",
    personas: [
      { t: "Asylum seekers", d: "Understand every letter from the migration authority without needing a translator." },
      { t: "International students", d: "Never miss a permit renewal, appointment, or deadline in an unfamiliar system." },
      { t: "Workers & families", d: "Keep a household's immigration documents organised in one place." },
    ],
    privacy_label: "Data handling",
    privacy_h: "Your documents never leave processing.",
    privacy_sub: "migraDOCS is designed around a strict minimum-retention principle.",
    privacy_points: [
      { t: "No file storage", d: "Original documents are processed in memory and discarded. Only the structured summary is retained." },
      { t: "Extracted fields only", d: "Dates, required actions, and categories — never the raw letter, never photographs of pages." },
      { t: "Auditable deletion", d: "Every summary can be permanently erased from your account at any time." },
    ],
    waitlist_h: "Be the first to know.",
    waitlist_sub: "Leave your email. We'll reach out when you can use it.",
    waitlist_placeholder: "you@email.com",
    waitlist_cta: "Join the waitlist",
    waitlist_joining: "Joining…",
    waitlist_ok_t: "You're on the list.",
    waitlist_ok_d: "We'll be in touch.",
    waitlist_err: "Please enter a valid email address.",
    footer_copy: "© 2026 migraDOCS",
    footer_disclaimer: "Structured information only. Not legal advice.",
  },
  DE: {
    dir: "ltr",
    nav_cta: "Warteliste beitreten",
    lang_label: "Sprache",
    hero_kicker: "STRUKTURIERTE INFORMATION · KEINE RECHTSBERATUNG",
    hero_h1_1: "Das Einwanderungssystem,",
    hero_h1_2: "übersetzt.",
    hero_sub: "Dokument hochladen. Inhalt verstehen. Wissen, was zu tun ist — und wann.",
    hero_cta: "Warteliste beitreten",
    hero_meta: "Keine Datei wird gespeichert. Verarbeitet und verworfen.",
    doc_plain: "Einfache Sprache",
    doc_deadline: "Frist",
    doc_action: "Erforderlich",
    docs: [
      { type: "Genehmigungsbescheid", auth: "Ausländerbehörde", date: "Ausgestellt 12. April 2026", translation: "Ihre Arbeitserlaubnis wurde genehmigt. Abholung persönlich innerhalb von 30 Tagen.", deadline: "12. Mai 2026", action: "Abholtermin buchen" },
      { type: "Terminanordnung", auth: "Biometrieerfassung", date: "Ausgestellt 03. April 2026", translation: "Ein biometrischer Termin wurde angesetzt. Erscheinen ist verpflichtend.", deadline: "28. April 2026", action: "Persönlich erscheinen" },
      { type: "Widerspruchsbescheid", auth: "Verwaltungsgericht", date: "Ausgestellt 21. März 2026", translation: "Ihr Widerspruch wird geprüft. Eine schriftliche Entscheidung ergeht binnen 60 Tagen.", deadline: "20. Mai 2026", action: "Schriftliche Mitteilung abwarten" },
      { type: "Nachforderung", auth: "Ausländerbehörde", date: "Ausgestellt 08. April 2026", translation: "Weitere Unterlagen sind erforderlich. Einreichung innerhalb von 14 Tagen, sonst Verfahrensaussetzung.", deadline: "22. April 2026", action: "3 Unterlagen einreichen" },
    ],
    how_label: "Ablauf",
    how_h: "So funktioniert es",
    how_sub: "Drei Schritte, ohne Fachjargon.",
    steps: [
      { n: "01", t: "Dokument hochladen", d: "Jede offizielle Mitteilung oder jeder Bescheid einer Ausländerbehörde." },
      { n: "02", t: "Wir erklären es", d: "Zusammenfassung in einfacher Sprache, Termine und Handlungsaufforderungen." },
      { n: "03", t: "Sie wissen, was zu tun ist", d: "Klare nächste Schritte und Fristen, in der richtigen Reihenfolge." },
    ],
    who_label: "Für wen",
    who_h: "Gemacht für Menschen im System.",
    who_sub: "Einwandernde, unterstützende Organisationen und beratende Anwältinnen.",
    personas: [
      { t: "Asylsuchende", d: "Jeden Behördenbrief verstehen — ohne Übersetzer." },
      { t: "Internationale Studierende", d: "Keine Verlängerung, kein Termin, keine Frist mehr verpassen." },
      { t: "Arbeitnehmer & Familien", d: "Alle Einwanderungsdokumente des Haushalts an einem Ort." },
    ],
    privacy_label: "Datenverarbeitung",
    privacy_h: "Ihre Dokumente verlassen die Verarbeitung nicht.",
    privacy_sub: "migraDOCS folgt einem strikten Prinzip der minimalen Datenaufbewahrung.",
    privacy_points: [
      { t: "Keine Dateispeicherung", d: "Originale werden im Arbeitsspeicher verarbeitet und verworfen. Nur die strukturierte Zusammenfassung bleibt." },
      { t: "Nur extrahierte Felder", d: "Termine, Pflichten, Kategorien — nie der Originaltext, nie Seitenfotos." },
      { t: "Prüfbare Löschung", d: "Jede Zusammenfassung kann jederzeit dauerhaft aus Ihrem Konto entfernt werden." },
    ],
    waitlist_h: "Erfahren Sie es zuerst.",
    waitlist_sub: "Hinterlassen Sie Ihre E-Mail-Adresse. Wir melden uns, sobald es losgeht.",
    waitlist_placeholder: "sie@email.de",
    waitlist_cta: "Warteliste beitreten",
    waitlist_joining: "Wird hinzugefügt…",
    waitlist_ok_t: "Sie stehen auf der Liste.",
    waitlist_ok_d: "Wir melden uns.",
    waitlist_err: "Bitte eine gültige E-Mail-Adresse eingeben.",
    footer_copy: "© 2026 migraDOCS",
    footer_disclaimer: "Nur strukturierte Information. Keine Rechtsberatung.",
  },
  SV: {
    dir: "ltr",
    nav_cta: "Gå med i väntelistan",
    lang_label: "Språk",
    hero_kicker: "STRUKTURERAD INFORMATION · INTE JURIDISK RÅDGIVNING",
    hero_h1_1: "Migrationssystemet,",
    hero_h1_2: "översatt.",
    hero_sub: "Ladda upp ett dokument. Förstå vad det betyder. Vet vad du ska göra — och när.",
    hero_cta: "Gå med i väntelistan",
    hero_meta: "Ingen fil lagras. Behandlas och raderas.",
    doc_plain: "Klarspråk",
    doc_deadline: "Sista dag",
    doc_action: "Krav",
    docs: [
      { type: "Tillståndsbesked", auth: "Migrationsverket", date: "Utfärdat 12 april 2026", translation: "Ditt arbetstillstånd har beviljats. Hämta personligen inom 30 dagar.", deadline: "12 maj 2026", action: "Boka hämtningstid" },
      { type: "Kallelse", auth: "Biometri", date: "Utfärdad 3 april 2026", translation: "Du har kallats till biometri. Närvaro är obligatorisk.", deadline: "28 april 2026", action: "Inställ dig personligen" },
      { type: "Överklagandebesked", auth: "Förvaltningsrätten", date: "Utfärdat 21 mars 2026", translation: "Ditt överklagande prövas. Skriftligt beslut inom 60 dagar.", deadline: "20 maj 2026", action: "Invänta skriftligt besked" },
      { type: "Komplettering", auth: "Migrationsverket", date: "Utfärdat 8 april 2026", translation: "Ytterligare handlingar krävs. Inlämning inom 14 dagar, annars vilar ärendet.", deadline: "22 april 2026", action: "Lämna in 3 handlingar" },
    ],
    how_label: "Process",
    how_h: "Så fungerar det",
    how_sub: "Tre steg, utan jargong.",
    steps: [
      { n: "01", t: "Ladda upp dokumentet", d: "Vilken officiell skrivelse eller vilket beslut som helst från en migrationsmyndighet." },
      { n: "02", t: "Vi förklarar det", d: "Sammanfattning i klarspråk, datum och vad som krävs av dig." },
      { n: "03", t: "Du vet vad du ska göra", d: "Tydliga nästa steg och frister, i rätt ordning." },
    ],
    who_label: "För vem",
    who_h: "Byggt för människor inuti systemet.",
    who_sub: "Enskilda migranter, organisationer som stödjer dem och jurister som rådger.",
    personas: [
      { t: "Asylsökande", d: "Förstå varje brev från myndigheten — utan tolk." },
      { t: "Internationella studenter", d: "Missa aldrig en förlängning, tid eller frist i ett obekant system." },
      { t: "Arbetstagare & familjer", d: "Hela hushållets migrationsdokument på ett ställe." },
    ],
    privacy_label: "Datahantering",
    privacy_h: "Dina dokument lämnar aldrig behandlingen.",
    privacy_sub: "migraDOCS är byggt kring strikt minimal datalagring.",
    privacy_points: [
      { t: "Ingen fillagring", d: "Original behandlas i minnet och raderas. Endast den strukturerade sammanfattningen sparas." },
      { t: "Endast extraherade fält", d: "Datum, åtgärder och kategorier — aldrig originalbrev, aldrig sidfoton." },
      { t: "Spårbar radering", d: "Varje sammanfattning kan raderas permanent från ditt konto när som helst." },
    ],
    waitlist_h: "Bli först med att få veta.",
    waitlist_sub: "Lämna din e-post. Vi hör av oss när det är din tur.",
    waitlist_placeholder: "du@email.se",
    waitlist_cta: "Gå med i väntelistan",
    waitlist_joining: "Lägger till…",
    waitlist_ok_t: "Du är med på listan.",
    waitlist_ok_d: "Vi hör av oss.",
    waitlist_err: "Ange en giltig e-postadress.",
    footer_copy: "© 2026 migraDOCS",
    footer_disclaimer: "Endast strukturerad information. Inte juridisk rådgivning.",
  },
  FR: {
    dir: "ltr",
    nav_cta: "Rejoindre la liste d'attente",
    lang_label: "Langue",
    hero_kicker: "INFORMATION STRUCTURÉE · PAS DE CONSEIL JURIDIQUE",
    hero_h1_1: "Le système d'immigration,",
    hero_h1_2: "traduit.",
    hero_sub: "Téléchargez un document. Comprenez ce qu'il signifie. Sachez quoi faire et quand.",
    hero_cta: "Rejoindre la liste d'attente",
    hero_meta: "Aucun fichier n'est stocké. Traité et supprimé.",
    doc_plain: "Langage clair",
    doc_deadline: "Échéance",
    doc_action: "Action requise",
    docs: [
      { type: "Avis de permis", auth: "Autorité d'immigration", date: "Délivré le 12 avril 2026", translation: "Votre permis de travail a été approuvé. Récupérez-le en personne dans les 30 jours.", deadline: "12 mai 2026", action: "Prendre rendez-vous" },
      { type: "Convocation", auth: "Services biométriques", date: "Délivré le 03 avril 2026", translation: "Vous avez un rendez-vous biométrique programmé. La présence est obligatoire.", deadline: "28 avril 2026", action: "Se présenter en personne" },
      { type: "Décision d'appel", auth: "Tribunal administratif", date: "Délivré le 21 mars 2026", translation: "Votre appel est en cours d'examen. Une décision écrite sera rendue dans 60 jours.", deadline: "20 mai 2026", action: "Attendre la notification" },
      { type: "Documents supplémentaires", auth: "Autorité d'immigration", date: "Délivré le 08 avril 2026", translation: "Des documents supplémentaires sont requis. Soumettez les éléments listés dans 14 jours ou votre dossier est suspendu.", deadline: "22 avril 2026", action: "Soumettre 3 documents" },
    ],
    how_label: "Processus",
    how_h: "Comment ça marche",
    how_sub: "Trois étapes, sans jargon.",
    steps: [
      { n: "01", t: "Téléchargez votre document", d: "Toute lettre ou avis officiel d'une autorité d'immigration." },
      { n: "02", t: "Nous l'expliquons", d: "Résumé en langage clair, dates et ce qui vous est demandé." },
      { n: "03", t: "Vous savez quoi faire", d: "Prochaines étapes claires et délais, dans le bon ordre." },
    ],
    who_label: "Pour qui",
    who_h: "Conçu pour les personnes dans le système.",
    who_sub: "Immigrants individuels, ONG qui les soutiennent, et avocats qui les conseillent.",
    personas: [
      { t: "Demandeurs d'asile", d: "Comprenez chaque lettre des autorités sans avoir besoin d'un traducteur." },
      { t: "Étudiants internationaux", d: "Ne manquez jamais un renouvellement, un rendez-vous ou une échéance." },
      { t: "Travailleurs et familles", d: "Gardez les documents d'immigration du foyer organisés en un seul endroit." },
    ],
    privacy_label: "Gestion des données",
    privacy_h: "Vos documents ne quittent jamais le traitement.",
    privacy_sub: "migraDOCS est conçu autour d'un principe strict de rétention minimale.",
    privacy_points: [
      { t: "Aucun stockage de fichier", d: "Les documents originaux sont traités en mémoire et supprimés. Seul le résumé structuré est conservé." },
      { t: "Champs extraits uniquement", d: "Dates, actions requises et catégories — jamais la lettre brute, jamais les photos de pages." },
      { t: "Suppression vérifiable", d: "Chaque résumé peut être définitivement effacé de votre compte à tout moment." },
    ],
    waitlist_h: "Soyez le premier informé.",
    waitlist_sub: "Laissez votre email. Nous vous contacterons quand vous pourrez l'utiliser.",
    waitlist_placeholder: "vous@email.com",
    waitlist_cta: "Rejoindre la liste d'attente",
    waitlist_joining: "Inscription…",
    waitlist_ok_t: "Vous êtes sur la liste.",
    waitlist_ok_d: "Nous vous contacterons.",
    waitlist_err: "Veuillez saisir une adresse email valide.",
    footer_copy: "© 2026 migraDOCS",
    footer_disclaimer: "Information structurée uniquement. Pas de conseil juridique.",
  },
  IT: {
    dir: "ltr",
    nav_cta: "Unisciti alla lista d'attesa",
    lang_label: "Lingua",
    hero_kicker: "INFORMAZIONE STRUTTURATA · NON CONSULENZA LEGALE",
    hero_h1_1: "Il sistema d'immigrazione,",
    hero_h1_2: "tradotto.",
    hero_sub: "Carica un documento. Capisci cosa significa. Sai cosa fare e quando.",
    hero_cta: "Unisciti alla lista d'attesa",
    hero_meta: "Nessun file viene conservato. Elaborato e scartato.",
    doc_plain: "Linguaggio semplice",
    doc_deadline: "Scadenza",
    doc_action: "Azione richiesta",
    docs: [
      { type: "Avviso di permesso", auth: "Autorità immigrazione", date: "Rilasciato il 12 aprile 2026", translation: "Il tuo permesso di lavoro è stato approvato. Ritiralo di persona entro 30 giorni.", deadline: "12 maggio 2026", action: "Prenotare il ritiro" },
      { type: "Lettera di convocazione", auth: "Servizi biometrici", date: "Rilasciato il 03 aprile 2026", translation: "Hai un appuntamento biometrico programmato. La presenza è obbligatoria.", deadline: "28 aprile 2026", action: "Presentarsi di persona" },
      { type: "Decisione di appello", auth: "Tribunale amministrativo", date: "Rilasciato il 21 marzo 2026", translation: "Il tuo ricorso è in esame. Una decisione scritta sarà emessa entro 60 giorni.", deadline: "20 maggio 2026", action: "Attendere la notifica" },
      { type: "Documentazione aggiuntiva", auth: "Autorità immigrazione", date: "Rilasciato l'08 aprile 2026", translation: "Sono richiesti ulteriori documenti. Invia gli elementi elencati entro 14 giorni o il tuo caso sarà sospeso.", deadline: "22 aprile 2026", action: "Inviare 3 documenti" },
    ],
    how_label: "Processo",
    how_h: "Come funziona",
    how_sub: "Tre passaggi, senza gergo.",
    steps: [
      { n: "01", t: "Carica il tuo documento", d: "Qualsiasi lettera o avviso ufficiale da un'autorità di immigrazione." },
      { n: "02", t: "Lo spieghiamo", d: "Riepilogo in linguaggio semplice, date e cosa ti viene chiesto." },
      { n: "03", t: "Sai cosa fare", d: "Prossimi passi chiari e scadenze, nell'ordine corretto." },
    ],
    who_label: "Per chi",
    who_h: "Creato per le persone nel sistema.",
    who_sub: "Immigrati individuali, ONG che li supportano, e avvocati che li consigliano.",
    personas: [
      { t: "Richiedenti asilo", d: "Capisci ogni lettera dall'autorità senza bisogno di un traduttore." },
      { t: "Studenti internazionali", d: "Non perdere mai un rinnovo, un appuntamento o una scadenza." },
      { t: "Lavoratori e famiglie", d: "Tieni organizzati i documenti di immigrazione della famiglia in un unico posto." },
    ],
    privacy_label: "Gestione dati",
    privacy_h: "I tuoi documenti non lasciano mai l'elaborazione.",
    privacy_sub: "migraDOCS è progettato attorno a un rigoroso principio di conservazione minima.",
    privacy_points: [
      { t: "Nessuna archiviazione", d: "I documenti originali vengono elaborati in memoria e scartati. Viene conservato solo il riepilogo strutturato." },
      { t: "Solo campi estratti", d: "Date, azioni richieste e categorie — mai la lettera grezza, mai le foto delle pagine." },
      { t: "Eliminazione verificabile", d: "Ogni riepilogo può essere eliminato definitivamente dal tuo account in qualsiasi momento." },
    ],
    waitlist_h: "Sii il primo a saperlo.",
    waitlist_sub: "Lascia la tua email. Ti contatteremo quando potrai usarlo.",
    waitlist_placeholder: "tu@email.it",
    waitlist_cta: "Unisciti alla lista d'attesa",
    waitlist_joining: "Iscrizione…",
    waitlist_ok_t: "Sei nella lista.",
    waitlist_ok_d: "Ti contatteremo.",
    waitlist_err: "Inserisci un indirizzo email valido.",
    footer_copy: "© 2026 migraDOCS",
    footer_disclaimer: "Solo informazioni strutturate. Non consulenza legale.",
  },
  PL: {
    dir: "ltr",
    nav_cta: "Dołącz do listy oczekujących",
    lang_label: "Język",
    hero_kicker: "INFORMACJA STRUKTURALNA · NIE PORADA PRAWNA",
    hero_h1_1: "System imigracyjny,",
    hero_h1_2: "przetłumaczony.",
    hero_sub: "Prześlij dokument. Zrozum, co oznacza. Wiedz, co zrobić i kiedy.",
    hero_cta: "Dołącz do listy oczekujących",
    hero_meta: "Żaden plik nie jest przechowywany. Przetworzony i usunięty.",
    doc_plain: "Prosty język",
    doc_deadline: "Termin",
    doc_action: "Wymagane działanie",
    docs: [
      { type: "Zawiadomienie o zezwoleniu", auth: "Urząd ds. cudzoziemców", date: "Wydano 12 kwietnia 2026", translation: "Twoje zezwolenie na pracę zostało zatwierdzone. Odbierz je osobiście w ciągu 30 dni.", deadline: "12 maja 2026", action: "Umów wizytę odbiorczą" },
      { type: "Wezwanie na spotkanie", auth: "Usługi biometryczne", date: "Wydano 03 kwietnia 2026", translation: "Masz zaplanowane spotkanie biometryczne. Obecność jest obowiązkowa.", deadline: "28 kwietnia 2026", action: "Stawić się osobiście" },
      { type: "Decyzja odwoławcza", auth: "Sąd administracyjny", date: "Wydano 21 marca 2026", translation: "Twoje odwołanie jest rozpatrywane. Pisemna decyzja zostanie wydana w ciągu 60 dni.", deadline: "20 maja 2026", action: "Oczekiwać powiadomienia" },
      { type: "Dodatkowa dokumentacja", auth: "Urząd ds. cudzoziemców", date: "Wydano 08 kwietnia 2026", translation: "Wymagane są dodatkowe dokumenty. Prześlij wymienione elementy w ciągu 14 dni, w przeciwnym razie sprawa zostanie zawieszona.", deadline: "22 kwietnia 2026", action: "Przesłać 3 dokumenty" },
    ],
    how_label: "Proces",
    how_h: "Jak to działa",
    how_sub: "Trzy kroki, bez żargonu.",
    steps: [
      { n: "01", t: "Prześlij dokument", d: "Dowolny oficjalny list lub powiadomienie od organu imigracyjnego." },
      { n: "02", t: "Wyjaśniamy", d: "Podsumowanie w prostym języku, daty i czego się od ciebie wymaga." },
      { n: "03", t: "Wiesz, co robić", d: "Jasne kolejne kroki i terminy, w odpowiedniej kolejności." },
    ],
    who_label: "Dla kogo",
    who_h: "Stworzone dla ludzi w systemie.",
    who_sub: "Indywidualni imigranci, NGO które ich wspierają, i prawnicy którzy doradzają.",
    personas: [
      { t: "Osoby ubiegające się o azyl", d: "Rozumiej każdy list od urzędu imigracyjnego bez tłumacza." },
      { t: "Studenci zagraniczni", d: "Nigdy nie przegap odnowienia, wizyty ani terminu w nieznanym systemie." },
      { t: "Pracownicy i rodziny", d: "Trzymaj dokumenty imigracyjne całej rodziny w jednym miejscu." },
    ],
    privacy_label: "Przetwarzanie danych",
    privacy_h: "Twoje dokumenty nigdy nie opuszczają przetwarzania.",
    privacy_sub: "migraDOCS jest zbudowany wokół zasady minimalnego przechowywania danych.",
    privacy_points: [
      { t: "Brak przechowywania plików", d: "Oryginalne dokumenty są przetwarzane w pamięci i usuwane. Zachowywane jest tylko ustrukturyzowane podsumowanie." },
      { t: "Tylko wyodrębnione pola", d: "Daty, wymagane działania i kategorie — nigdy oryginalny list, nigdy zdjęcia stron." },
      { t: "Weryfikowalne usunięcie", d: "Każde podsumowanie można trwale usunąć z konta w dowolnym momencie." },
    ],
    waitlist_h: "Bądź pierwszym, który się dowie.",
    waitlist_sub: "Zostaw swój email. Skontaktujemy się z tobą.",
    waitlist_placeholder: "ty@email.pl",
    waitlist_cta: "Dołącz do listy oczekujących",
    waitlist_joining: "Dołączanie…",
    waitlist_ok_t: "Jesteś na liście.",
    waitlist_ok_d: "Skontaktujemy się z tobą.",
    waitlist_err: "Proszę podać prawidłowy adres email.",
    footer_copy: "© 2026 migraDOCS",
    footer_disclaimer: "Tylko informacje strukturalne. Nie porada prawna.",
  },
  UK: {
    dir: "ltr",
    nav_cta: "Приєднатися до списку очікування",
    lang_label: "Мова",
    hero_kicker: "СТРУКТУРОВАНА ІНФОРМАЦІЯ · НЕ ЮРИДИЧНА ПОРАДА",
    hero_h1_1: "Імміграційна система,",
    hero_h1_2: "пояснена.",
    hero_sub: "Завантажте документ. Зрозумійте його зміст. Знайте, що робити і коли.",
    hero_cta: "Приєднатися до списку очікування",
    hero_meta: "Жоден файл не зберігається. Обробляється і видаляється.",
    doc_plain: "Проста мова",
    doc_deadline: "Термін",
    doc_action: "Необхідна дія",
    docs: [
      { type: "Повідомлення про дозвіл", auth: "Імміграційний орган", date: "Видано 12 квітня 2026", translation: "Ваш дозвіл на роботу затверджено. Отримайте його особисто протягом 30 днів.", deadline: "12 травня 2026", action: "Записатися на отримання" },
      { type: "Запрошення на прийом", auth: "Служба біометрії", date: "Видано 03 квітня 2026", translation: "Вас записано на біометричний прийом. Відвідування обов'язкове.", deadline: "28 квітня 2026", action: "Прийти особисто" },
      { type: "Рішення з апеляції", auth: "Адміністративний суд", date: "Видано 21 березня 2026", translation: "Ваша апеляція розглядається. Письмове рішення буде видано протягом 60 днів.", deadline: "20 травня 2026", action: "Очікувати повідомлення" },
      { type: "Додаткові документи", auth: "Імміграційний орган", date: "Видано 08 квітня 2026", translation: "Необхідні додаткові документи. Подайте зазначені матеріали протягом 14 днів, інакше справу буде призупинено.", deadline: "22 квітня 2026", action: "Подати 3 документи" },
    ],
    how_label: "Процес",
    how_h: "Як це працює",
    how_sub: "Три кроки, без жаргону.",
    steps: [
      { n: "01", t: "Завантажте документ", d: "Будь-який офіційний лист або повідомлення від імміграційного органу." },
      { n: "02", t: "Ми пояснюємо", d: "Резюме простою мовою, дати та що від вас вимагається." },
      { n: "03", t: "Ви знаєте, що робити", d: "Чіткі наступні кроки та терміни, у правильному порядку." },
    ],
    who_label: "Для кого",
    who_h: "Створено для людей у системі.",
    who_sub: "Окремі мігранти, НКО що їх підтримують, та юристи що консультують.",
    personas: [
      { t: "Шукачі притулку", d: "Розумійте кожен лист від міграційного органу без перекладача." },
      { t: "Міжнародні студенти", d: "Ніколи не пропускайте поновлення, прийом або термін." },
      { t: "Працівники та сім'ї", d: "Зберігайте імміграційні документи сім'ї в одному місці." },
    ],
    privacy_label: "Обробка даних",
    privacy_h: "Ваші документи ніколи не залишають обробку.",
    privacy_sub: "migraDOCS побудований на принципі суворого мінімального зберігання даних.",
    privacy_points: [
      { t: "Без зберігання файлів", d: "Оригінальні документи обробляються в пам'яті та видаляються. Зберігається лише структуроване резюме." },
      { t: "Лише витягнуті поля", d: "Дати, необхідні дії та категорії — ніколи оригінальний текст, ніколи фотографії сторінок." },
      { t: "Перевірюване видалення", d: "Будь-яке резюме може бути назавжди видалено з вашого облікового запису будь-коли." },
    ],
    waitlist_h: "Дізнайтеся першими.",
    waitlist_sub: "Залиште свою електронну пошту. Ми зв'яжемося з вами.",
    waitlist_placeholder: "ви@email.com",
    waitlist_cta: "Приєднатися до списку очікування",
    waitlist_joining: "Додавання…",
    waitlist_ok_t: "Ви в списку.",
    waitlist_ok_d: "Ми зв'яжемося з вами.",
    waitlist_err: "Будь ласка, введіть дійсну адресу електронної пошти.",
    footer_copy: "© 2026 migraDOCS",
    footer_disclaimer: "Лише структурована інформація. Не юридична порада.",
  },
  ES: {
    dir: "ltr",
    nav_cta: "Unirse a la lista de espera",
    lang_label: "Idioma",
    hero_kicker: "INFORMACIÓN ESTRUCTURADA · NO ASESORAMIENTO LEGAL",
    hero_h1_1: "El sistema de inmigración,",
    hero_h1_2: "traducido.",
    hero_sub: "Sube un documento. Entiende lo que significa. Sabe qué hacer y cuándo.",
    hero_cta: "Unirse a la lista de espera",
    hero_meta: "Ningún archivo se almacena. Procesado y eliminado.",
    doc_plain: "Lenguaje claro",
    doc_deadline: "Fecha límite",
    doc_action: "Acción requerida",
    docs: [
      { type: "Aviso de permiso", auth: "Autoridad de inmigración", date: "Emitido el 12 de abril de 2026", translation: "Su permiso de trabajo ha sido aprobado. Recójalo en persona dentro de 30 días.", deadline: "12 de mayo de 2026", action: "Reservar cita de recogida" },
      { type: "Carta de cita", auth: "Servicios biométricos", date: "Emitido el 03 de abril de 2026", translation: "Tiene programada una cita biométrica. La asistencia es obligatoria.", deadline: "28 de abril de 2026", action: "Presentarse en persona" },
      { type: "Resolución de apelación", auth: "Tribunal administrativo", date: "Emitido el 21 de marzo de 2026", translation: "Su apelación está siendo revisada. Se emitirá una resolución escrita en 60 días.", deadline: "20 de mayo de 2026", action: "Esperar notificación escrita" },
      { type: "Documentación adicional", auth: "Autoridad de inmigración", date: "Emitido el 08 de abril de 2026", translation: "Se requieren documentos adicionales. Envíe los elementos listados en 14 días o su caso será suspendido.", deadline: "22 de abril de 2026", action: "Enviar 3 documentos" },
    ],
    how_label: "Proceso",
    how_h: "Cómo funciona",
    how_sub: "Tres pasos, sin jerga.",
    steps: [
      { n: "01", t: "Sube tu documento", d: "Cualquier carta o aviso oficial de una autoridad de inmigración." },
      { n: "02", t: "Lo explicamos", d: "Resumen en lenguaje claro, fechas y lo que se te pide." },
      { n: "03", t: "Sabes qué hacer", d: "Próximos pasos claros y plazos, en el orden correcto." },
    ],
    who_label: "Para quién",
    who_h: "Creado para personas dentro del sistema.",
    who_sub: "Inmigrantes individuales, ONG que los apoyan y abogados que los asesoran.",
    personas: [
      { t: "Solicitantes de asilo", d: "Entiende cada carta de la autoridad sin necesitar un traductor." },
      { t: "Estudiantes internacionales", d: "Nunca pierdas una renovación, cita o plazo en un sistema desconocido." },
      { t: "Trabajadores y familias", d: "Mantén los documentos de inmigración del hogar organizados en un solo lugar." },
    ],
    privacy_label: "Manejo de datos",
    privacy_h: "Tus documentos nunca salen del procesamiento.",
    privacy_sub: "migraDOCS está diseñado en torno a un principio estricto de retención mínima.",
    privacy_points: [
      { t: "Sin almacenamiento de archivos", d: "Los documentos originales se procesan en memoria y se descartan. Solo se conserva el resumen estructurado." },
      { t: "Solo campos extraídos", d: "Fechas, acciones requeridas y categorías — nunca la carta original, nunca fotos de páginas." },
      { t: "Eliminación auditable", d: "Cada resumen puede borrarse permanentemente de tu cuenta en cualquier momento." },
    ],
    waitlist_h: "Sé el primero en saberlo.",
    waitlist_sub: "Deja tu email. Te contactaremos cuando puedas usarlo.",
    waitlist_placeholder: "tu@email.com",
    waitlist_cta: "Unirse a la lista de espera",
    waitlist_joining: "Uniéndose…",
    waitlist_ok_t: "Estás en la lista.",
    waitlist_ok_d: "Te contactaremos.",
    waitlist_err: "Por favor introduce una dirección de email válida.",
    footer_copy: "© 2026 migraDOCS",
    footer_disclaimer: "Solo información estructurada. No asesoramiento legal.",
  },
  TR: {
    dir: "ltr",
    nav_cta: "Bekleme listesine katıl",
    lang_label: "Dil",
    hero_kicker: "YAPILANDIRILMIŞ BİLGİ · HUKUKİ DANIŞMANLIK DEĞİLDİR",
    hero_h1_1: "Göçmenlik sistemi,",
    hero_h1_2: "çevrildi.",
    hero_sub: "Bir belge yükle. Ne anlama geldiğini anla. Ne yapman gerektiğini ve ne zaman biliyorsun.",
    hero_cta: "Bekleme listesine katıl",
    hero_meta: "Hiçbir dosya saklanmaz. İşlenir ve silinir.",
    doc_plain: "Sade dil",
    doc_deadline: "Son tarih",
    doc_action: "Gerekli işlem",
    docs: [
      { type: "İzin bildirimi", auth: "Göçmenlik Makamı", date: "12 Nisan 2026 tarihinde düzenlendi", translation: "Çalışma izniniz onaylandı. 30 gün içinde şahsen alın.", deadline: "12 Mayıs 2026", action: "Teslim alma randevusu al" },
      { type: "Randevu mektubu", auth: "Biyometrik Hizmetler", date: "03 Nisan 2026 tarihinde düzenlendi", translation: "Biyometrik randevunuz programlandı. Katılım zorunludur.", deadline: "28 Nisan 2026", action: "Şahsen katıl" },
      { type: "İtiraz kararı", auth: "İdare Mahkemesi", date: "21 Mart 2026 tarihinde düzenlendi", translation: "İtirazınız inceleniyor. 60 gün içinde yazılı karar verilecek.", deadline: "20 Mayıs 2026", action: "Yazılı bildirimi bekle" },
      { type: "Ek belgeler", auth: "Göçmenlik Makamı", date: "08 Nisan 2026 tarihinde düzenlendi", translation: "Ek belgeler gereklidir. 14 gün içinde gönderin, aksi takdirde davanız askıya alınır.", deadline: "22 Nisan 2026", action: "3 belge gönder" },
    ],
    how_label: "Süreç",
    how_h: "Nasıl çalışır",
    how_sub: "Üç adım, jargon yok.",
    steps: [
      { n: "01", t: "Belgenizi yükleyin", d: "Göçmenlik makamından gelen resmi herhangi bir mektup veya bildirim." },
      { n: "02", t: "Açıklıyoruz", d: "Sade dilde özet, tarihler ve sizden ne istendiği." },
      { n: "03", t: "Ne yapacağınızı biliyorsunuz", d: "Net sonraki adımlar ve son tarihler, doğru sırayla." },
    ],
    who_label: "Kimler için",
    who_h: "Sistem içindeki insanlar için oluşturuldu.",
    who_sub: "Bireysel göçmenler, onları destekleyen STK'lar ve onlara danışmanlık yapan avukatlar.",
    personas: [
      { t: "Sığınmacılar", d: "Göçmenlik makamından gelen her mektubu tercümana gerek duymadan anlayın." },
      { t: "Uluslararası öğrenciler", d: "Tanımadığınız bir sistemde hiçbir uzatma, randevu veya son tarihi kaçırmayın." },
      { t: "Çalışanlar ve aileler", d: "Hane halkının göçmenlik belgelerini tek bir yerde düzenli tutun." },
    ],
    privacy_label: "Veri işleme",
    privacy_h: "Belgeleriniz hiçbir zaman işlemeyi terk etmez.",
    privacy_sub: "migraDOCS, katı minimum saklama ilkesi etrafında tasarlanmıştır.",
    privacy_points: [
      { t: "Dosya depolama yok", d: "Orijinal belgeler bellekte işlenir ve atılır. Yalnızca yapılandırılmış özet saklanır." },
      { t: "Yalnızca çıkarılan alanlar", d: "Tarihler, gerekli eylemler ve kategoriler — hiçbir zaman ham mektup, hiçbir zaman sayfa fotoğrafları." },
      { t: "Denetlenebilir silme", d: "Her özet, hesabınızdan istediğiniz zaman kalıcı olarak silinebilir." },
    ],
    waitlist_h: "İlk öğrenen siz olun.",
    waitlist_sub: "E-postanızı bırakın. Kullanabildiğinizde size ulaşacağız.",
    waitlist_placeholder: "siz@email.com",
    waitlist_cta: "Bekleme listesine katıl",
    waitlist_joining: "Katılıyor…",
    waitlist_ok_t: "Listedesiniz.",
    waitlist_ok_d: "Size ulaşacağız.",
    waitlist_err: "Lütfen geçerli bir e-posta adresi girin.",
    footer_copy: "© 2026 migraDOCS",
    footer_disclaimer: "Yalnızca yapılandırılmış bilgi. Hukuki danışmanlık değildir.",
  },
  RO: {
    dir: "ltr",
    nav_cta: "Alătură-te listei de așteptare",
    lang_label: "Limbă",
    hero_kicker: "INFORMAȚIE STRUCTURATĂ · NU CONSULTANȚĂ JURIDICĂ",
    hero_h1_1: "Sistemul de imigrare,",
    hero_h1_2: "tradus.",
    hero_sub: "Încarcă un document. Înțelege ce înseamnă. Știi ce să faci și când.",
    hero_cta: "Alătură-te listei de așteptare",
    hero_meta: "Niciun fișier nu este stocat. Procesat și eliminat.",
    doc_plain: "Limbaj clar",
    doc_deadline: "Termen limită",
    doc_action: "Acțiune necesară",
    docs: [
      { type: "Aviz de permis", auth: "Autoritatea de imigrare", date: "Emis pe 12 aprilie 2026", translation: "Permisul tău de muncă a fost aprobat. Ridică-l personal în 30 de zile.", deadline: "12 mai 2026", action: "Programează ridicarea" },
      { type: "Scrisoare de programare", auth: "Servicii biometrice", date: "Emis pe 03 aprilie 2026", translation: "Ai o programare biometrică. Prezența este obligatorie.", deadline: "28 aprilie 2026", action: "Prezintă-te personal" },
      { type: "Decizie de apel", auth: "Tribunal administrativ", date: "Emis pe 21 martie 2026", translation: "Apelul tău este în curs de analiză. O decizie scrisă va fi emisă în 60 de zile.", deadline: "20 mai 2026", action: "Așteaptă notificarea" },
      { type: "Documentație suplimentară", auth: "Autoritatea de imigrare", date: "Emis pe 08 aprilie 2026", translation: "Sunt necesare documente suplimentare. Trimite elementele listate în 14 zile sau cazul tău va fi suspendat.", deadline: "22 aprilie 2026", action: "Trimite 3 documente" },
    ],
    how_label: "Proces",
    how_h: "Cum funcționează",
    how_sub: "Trei pași, fără jargon.",
    steps: [
      { n: "01", t: "Încarcă documentul tău", d: "Orice scrisoare sau aviz oficial de la o autoritate de imigrare." },
      { n: "02", t: "Îl explicăm", d: "Rezumat în limbaj clar, date și ce ți se cere." },
      { n: "03", t: "Știi ce să faci", d: "Pași următori clari și termene limită, în ordinea corectă." },
    ],
    who_label: "Pentru cine",
    who_h: "Construit pentru persoanele din sistem.",
    who_sub: "Imigranți individuali, ONG-uri care îi sprijină și avocați care îi consiliază.",
    personas: [
      { t: "Solicitanți de azil", d: "Înțelege fiecare scrisoare de la autoritate fără a avea nevoie de un traducător." },
      { t: "Studenți internaționali", d: "Nu rata niciodată o reînnoire, o programare sau un termen limită." },
      { t: "Lucrători și familii", d: "Ține documentele de imigrare ale gospodăriei organizate într-un singur loc." },
    ],
    privacy_label: "Gestionarea datelor",
    privacy_h: "Documentele tale nu părăsesc niciodată procesarea.",
    privacy_sub: "migraDOCS este proiectat în jurul unui principiu strict de retenție minimă.",
    privacy_points: [
      { t: "Fără stocare de fișiere", d: "Documentele originale sunt procesate în memorie și eliminate. Se păstrează doar rezumatul structurat." },
      { t: "Doar câmpuri extrase", d: "Date, acțiuni necesare și categorii — niciodată scrisoarea brută, niciodată fotografii ale paginilor." },
      { t: "Ștergere auditabilă", d: "Orice rezumat poate fi șters permanent din contul tău în orice moment." },
    ],
    waitlist_h: "Fii primul care află.",
    waitlist_sub: "Lasă emailul tău. Te vom contacta când îl poți folosi.",
    waitlist_placeholder: "tu@email.ro",
    waitlist_cta: "Alătură-te listei de așteptare",
    waitlist_joining: "Se alătură…",
    waitlist_ok_t: "Ești pe listă.",
    waitlist_ok_d: "Te vom contacta.",
    waitlist_err: "Te rugăm să introduci o adresă de email validă.",
    footer_copy: "© 2026 migraDOCS",
    footer_disclaimer: "Doar informații structurate. Nu consultanță juridică.",
  },
  HU: {
    dir: "ltr",
    nav_cta: "Csatlakozz a várólistához",
    lang_label: "Nyelv",
    hero_kicker: "STRUKTURÁLT INFORMÁCIÓ · NEM JOGI TANÁCSADÁS",
    hero_h1_1: "A bevándorlási rendszer,",
    hero_h1_2: "lefordítva.",
    hero_sub: "Töltsd fel a dokumentumodat. Értsd meg, mit jelent. Tudd, mit kell tenned és mikor.",
    hero_cta: "Csatlakozz a várólistához",
    hero_meta: "Egyetlen fájl sem kerül tárolásra. Feldolgozva és törölve.",
    doc_plain: "Egyszerű nyelv",
    doc_deadline: "Határidő",
    doc_action: "Szükséges lépés",
    docs: [
      { type: "Engedély értesítő", auth: "Bevándorlási Hatóság", date: "Kiadva 2026. április 12.", translation: "Munkavállalási engedélyedet jóváhagyták. Vedd át személyesen 30 napon belül.", deadline: "2026. május 12.", action: "Átvételi időpont foglalása" },
      { type: "Időpontlevél", auth: "Biometriai Szolgálat", date: "Kiadva 2026. április 03.", translation: "Biometriai időpontot kaptál. A megjelenés kötelező.", deadline: "2026. április 28.", action: "Személyes megjelenés" },
      { type: "Fellebbezési határozat", auth: "Közigazgatási Bíróság", date: "Kiadva 2026. március 21.", translation: "A fellebbezésed elbírálás alatt áll. Írásos döntés 60 napon belül születik.", deadline: "2026. május 20.", action: "Írásos értesítésre várni" },
      { type: "Pótlólagos dokumentumok", auth: "Bevándorlási Hatóság", date: "Kiadva 2026. április 08.", translation: "További dokumentumok szükségesek. Nyújtsd be a felsorolt iratokat 14 napon belül, vagy az ügyedet felfüggesztik.", deadline: "2026. április 22.", action: "3 dokumentum benyújtása" },
    ],
    how_label: "Folyamat",
    how_h: "Hogyan működik",
    how_sub: "Három lépés, zsargon nélkül.",
    steps: [
      { n: "01", t: "Töltsd fel a dokumentumodat", d: "Bármely hivatalos levél vagy értesítés bevándorlási hatóságtól." },
      { n: "02", t: "Mi megmagyarázzuk", d: "Egyszerű nyelvű összefoglaló, dátumok és mi várható tőled." },
      { n: "03", t: "Tudod, mit kell tenned", d: "Egyértelmű következő lépések és határidők, helyes sorrendben." },
    ],
    who_label: "Kinek szól",
    who_h: "A rendszerben lévő embereknek készült.",
    who_sub: "Egyéni bevándorlók, az őket támogató NGO-k és tanácsadó ügyvédek.",
    personas: [
      { t: "Menedékkérők", d: "Értsd meg minden hatósági levelet fordító nélkül." },
      { t: "Külföldi hallgatók", d: "Soha ne maradj le megújításról, időpontról vagy határidőről." },
      { t: "Munkavállalók és családok", d: "Tartsd egy helyen a háztartás összes bevándorlási dokumentumát." },
    ],
    privacy_label: "Adatkezelés",
    privacy_h: "Dokumentumaid soha nem hagyják el a feldolgozást.",
    privacy_sub: "A migraDOCS a minimális adatmegőrzés szigorú elvére épül.",
    privacy_points: [
      { t: "Nincs fájltárolás", d: "Az eredeti dokumentumokat a memóriában dolgozzuk fel, majd töröljük. Csak a strukturált összefoglaló marad meg." },
      { t: "Csak kinyert mezők", d: "Dátumok, szükséges lépések és kategóriák — soha az eredeti levél, soha oldalfotók." },
      { t: "Auditálható törlés", d: "Bármely összefoglaló bármikor véglegesen törölhető a fiókodból." },
    ],
    waitlist_h: "Légy az első, aki megtudja.",
    waitlist_sub: "Hagyd itt az emailcímed. Értesítünk, ha elérhető.",
    waitlist_placeholder: "te@email.hu",
    waitlist_cta: "Csatlakozz a várólistához",
    waitlist_joining: "Csatlakozás…",
    waitlist_ok_t: "Felkerültél a listára.",
    waitlist_ok_d: "Hamarosan jelentkezünk.",
    waitlist_err: "Kérjük, adj meg érvényes e-mail-címet.",
    footer_copy: "© 2026 migraDOCS",
    footer_disclaimer: "Csak strukturált információ. Nem jogi tanácsadás.",
  },
  RU: {
    dir: "ltr",
    nav_cta: "Присоединиться к списку ожидания",
    lang_label: "Язык",
    hero_kicker: "СТРУКТУРИРОВАННАЯ ИНФОРМАЦИЯ · НЕ ЮРИДИЧЕСКАЯ КОНСУЛЬТАЦИЯ",
    hero_h1_1: "Иммиграционная система,",
    hero_h1_2: "объяснена.",
    hero_sub: "Загрузите документ. Поймите, что он означает. Знайте, что делать и когда.",
    hero_cta: "Присоединиться к списку ожидания",
    hero_meta: "Ни один файл не хранится. Обрабатывается и удаляется.",
    doc_plain: "Простой язык",
    doc_deadline: "Срок",
    doc_action: "Необходимое действие",
    docs: [
      { type: "Уведомление о разрешении", auth: "Иммиграционный орган", date: "Выдано 12 апреля 2026", translation: "Ваше разрешение на работу одобрено. Получите его лично в течение 30 дней.", deadline: "12 мая 2026", action: "Записаться на получение" },
      { type: "Письмо о встрече", auth: "Биометрическая служба", date: "Выдано 03 апреля 2026", translation: "Вам назначена биометрическая встреча. Присутствие обязательно.", deadline: "28 апреля 2026", action: "Явиться лично" },
      { type: "Решение по апелляции", auth: "Административный суд", date: "Выдано 21 марта 2026", translation: "Ваша апелляция рассматривается. Письменное решение будет вынесено в течение 60 дней.", deadline: "20 мая 2026", action: "Ожидать письменного уведомления" },
      { type: "Дополнительные документы", auth: "Иммиграционный орган", date: "Выдано 08 апреля 2026", translation: "Необходимы дополнительные документы. Подайте указанные материалы в течение 14 дней, иначе дело будет приостановлено.", deadline: "22 апреля 2026", action: "Подать 3 документа" },
    ],
    how_label: "Процесс",
    how_h: "Как это работает",
    how_sub: "Три шага, без жаргона.",
    steps: [
      { n: "01", t: "Загрузите документ", d: "Любое официальное письмо или уведомление от иммиграционного органа." },
      { n: "02", t: "Мы объясняем", d: "Краткое изложение простым языком, даты и что от вас требуется." },
      { n: "03", t: "Вы знаете, что делать", d: "Чёткие следующие шаги и сроки в правильном порядке." },
    ],
    who_label: "Для кого",
    who_h: "Создано для людей внутри системы.",
    who_sub: "Отдельные мигранты, НКО которые их поддерживают, и юристы которые консультируют.",
    personas: [
      { t: "Соискатели убежища", d: "Понимайте каждое письмо от миграционного органа без переводчика." },
      { t: "Иностранные студенты", d: "Никогда не пропускайте продление, приём или срок в незнакомой системе." },
      { t: "Работники и семьи", d: "Храните иммиграционные документы семьи в одном месте." },
    ],
    privacy_label: "Обработка данных",
    privacy_h: "Ваши документы никогда не покидают обработку.",
    privacy_sub: "migraDOCS построен на принципе строгого минимального хранения данных.",
    privacy_points: [
      { t: "Без хранения файлов", d: "Оригинальные документы обрабатываются в памяти и удаляются. Хранится только структурированное резюме." },
      { t: "Только извлечённые поля", d: "Даты, необходимые действия и категории — никогда оригинальный текст, никогда фотографии страниц." },
      { t: "Проверяемое удаление", d: "Любое резюме может быть навсегда удалено из вашего аккаунта в любое время." },
    ],
    waitlist_h: "Узнайте первыми.",
    waitlist_sub: "Оставьте свою почту. Мы свяжемся с вами когда будет готово.",
    waitlist_placeholder: "вы@email.com",
    waitlist_cta: "Присоединиться к списку ожидания",
    waitlist_joining: "Присоединение…",
    waitlist_ok_t: "Вы в списке.",
    waitlist_ok_d: "Мы свяжемся с вами.",
    waitlist_err: "Пожалуйста, введите действительный адрес электронной почты.",
    footer_copy: "© 2026 migraDOCS",
    footer_disclaimer: "Только структурированная информация. Не юридическая консультация.",
  },
  FA: {
    dir: "rtl",
    nav_cta: "پیوستن به لیست انتظار",
    lang_label: "زبان",
    hero_kicker: "اطلاعات ساختاریافته · مشاوره حقوقی نیست",
    hero_h1_1: "سیستم مهاجرت،",
    hero_h1_2: "ترجمه شد.",
    hero_sub: "یک سند آپلود کنید. بفهمید چه معنایی دارد. بدانید چه باید بکنید و چه وقت.",
    hero_cta: "پیوستن به لیست انتظار",
    hero_meta: "هیچ فایلی ذخیره نمی‌شود. پردازش و حذف می‌شود.",
    doc_plain: "زبان ساده",
    doc_deadline: "مهلت",
    doc_action: "اقدام لازم",
    docs: [
      { type: "اطلاعیه مجوز", auth: "اداره مهاجرت", date: "صادر شده ۱۲ آوریل ۲۰۲۶", translation: "مجوز کار شما تأیید شده است. آن را ظرف ۳۰ روز شخصاً دریافت کنید.", deadline: "۱۲ مه ۲۰۲۶", action: "رزرو وقت دریافت" },
      { type: "نامه وقت ملاقات", auth: "خدمات بیومتریک", date: "صادر شده ۳ آوریل ۲۰۲۶", translation: "وقت ملاقات بیومتریک برای شما تعیین شده است. حضور اجباری است.", deadline: "۲۸ آوریل ۲۰۲۶", action: "حضور شخصی" },
      { type: "تصمیم استیناف", auth: "دادگاه اداری", date: "صادر شده ۲۱ مارس ۲۰۲۶", translation: "استیناف شما در حال بررسی است. تصمیم کتبی ظرف ۶۰ روز صادر خواهد شد.", deadline: "۲۰ مه ۲۰۲۶", action: "انتظار برای اطلاعیه کتبی" },
      { type: "مدارک اضافی", auth: "اداره مهاجرت", date: "صادر شده ۸ آوریل ۲۰۲۶", translation: "مدارک اضافی لازم است. موارد ذکر شده را ظرف ۱۴ روز ارسال کنید وگرنه پرونده شما معلق می‌شود.", deadline: "۲۲ آوریل ۲۰۲۶", action: "ارسال ۳ مدرک" },
    ],
    how_label: "فرآیند",
    how_h: "چطور کار می‌کند",
    how_sub: "سه مرحله، بدون اصطلاحات پیچیده.",
    steps: [
      { n: "۰۱", t: "سند خود را آپلود کنید", d: "هر نامه یا اطلاعیه رسمی از یک اداره مهاجرت." },
      { n: "۰۲", t: "ما توضیح می‌دهیم", d: "خلاصه به زبان ساده، تاریخ‌ها و آنچه از شما خواسته شده است." },
      { n: "۰۳", t: "می‌دانید چه کار کنید", d: "گام‌های بعدی روشن و مهلت‌ها، به ترتیب صحیح." },
    ],
    who_label: "برای چه کسی",
    who_h: "ساخته شده برای افراد داخل سیستم.",
    who_sub: "مهاجران فردی، سازمان‌های غیردولتی که از آن‌ها حمایت می‌کنند، و وکلایی که مشاوره می‌دهند.",
    personas: [
      { t: "پناهجویان", d: "هر نامه از اداره مهاجرت را بدون نیاز به مترجم درک کنید." },
      { t: "دانشجویان بین‌المللی", d: "هرگز تمدید، قرار ملاقات یا مهلتی را از دست ندهید." },
      { t: "کارگران و خانواده‌ها", d: "اسناد مهاجرتی خانواده را در یک مکان سازماندهی کنید." },
    ],
    privacy_label: "مدیریت داده",
    privacy_h: "اسناد شما هرگز پردازش را ترک نمی‌کنند.",
    privacy_sub: "migraDOCS بر اساس اصل نگهداری حداقل داده طراحی شده است.",
    privacy_points: [
      { t: "بدون ذخیره‌سازی فایل", d: "اسناد اصلی در حافظه پردازش و دور ریخته می‌شوند. فقط خلاصه ساختاریافته نگهداری می‌شود." },
      { t: "فقط فیلدهای استخراج شده", d: "تاریخ‌ها، اقدامات لازم و دسته‌بندی‌ها — هرگز نامه اصلی، هرگز عکس‌های صفحات." },
      { t: "حذف قابل حسابرسی", d: "هر خلاصه می‌تواند در هر زمانی به طور دائمی از حساب شما پاک شود." },
    ],
    waitlist_h: "اول بدانید.",
    waitlist_sub: "ایمیل خود را بگذارید. وقتی آماده شد با شما تماس می‌گیریم.",
    waitlist_placeholder: "شما@email.com",
    waitlist_cta: "پیوستن به لیست انتظار",
    waitlist_joining: "در حال پیوستن…",
    waitlist_ok_t: "شما در لیست هستید.",
    waitlist_ok_d: "با شما تماس خواهیم گرفت.",
    waitlist_err: "لطفاً یک آدرس ایمیل معتبر وارد کنید.",
    footer_copy: "© ۲۰۲۶ migraDOCS",
    footer_disclaimer: "فقط اطلاعات ساختاریافته. مشاوره حقوقی نیست.",
  },
  SO: {
    dir: "ltr",
    nav_cta: "Ku biir liiska sugitaanka",
    lang_label: "Luqad",
    hero_kicker: "MACLUUMAAD HABAYN · MAAHA TALLO SHARCI",
    hero_h1_1: "Nidaamka socdaalka,",
    hero_h1_2: "la turjumay.",
    hero_sub: "Soo geli dukumenti. Fahm waxa ay ka dhigan tahay. Ogow waxa aad samayn lahayd iyo goorta.",
    hero_cta: "Ku biir liiska sugitaanka",
    hero_meta: "Faylka laguma keydsan. Waa la hawlgalaa oo la tirtiray.",
    doc_plain: "Luqad fudud",
    doc_deadline: "Xaddi waqtiga",
    doc_action: "Tallaabada loo baahan yahay",
    docs: [
      { type: "Ogeysiiska ruqsadda", auth: "Hay'adda Socdaalka", date: "La soo saaray 12 Abriil 2026", translation: "Ruqsaddaada shaqada waa la ansixiyay. Qaado shakhsi ahaan 30 maalmood gudahood.", deadline: "12 Mey 2026", action: "Ballan u qabso qaadashada" },
      { type: "Warqadda ballanqaadka", auth: "Adeegyada Baayomeetrika", date: "La soo saaray 03 Abriil 2026", translation: "Ballan baayomeetri ayaa kugu qorsheeyay. Soo jeeda waa waajib.", deadline: "28 Abriil 2026", action: "Shakhsi ahaan soo gal" },
      { type: "Go'aanka dacwada", auth: "Maxkamadda Maamulka", date: "La soo saaray 21 Maarso 2026", translation: "Dacwadaadu waxay ku jirtaa dib u eegista. Go'aan qoran ayaa la siidayn doonaa 60 maalmood gudahood.", deadline: "20 Mey 2026", action: "Sug ogeysiiska qoran" },
      { type: "Dukumantiyo dheeraad ah", auth: "Hay'adda Socdaalka", date: "La soo saaray 08 Abriil 2026", translation: "Dukumantiyo dheeraad ah ayaa loo baahan yahay. Soo gudbi sheybaarka 14 maalmood gudahood ama kiiskaagu waanu la joogsanayaa.", deadline: "22 Abriil 2026", action: "Soo gudbi 3 dukumantiyo" },
    ],
    how_label: "Habka",
    how_h: "Sida ay u shaqaysaa",
    how_sub: "Saddex tallaabo, aan jargon lahayn.",
    steps: [
      { n: "01", t: "Soo geli dukumentikaaga", d: "Warqad rasmi ah ama ogeysiis ka yimaada hay'adda socdaalka." },
      { n: "02", t: "Waxaan sharaxnaa", d: "Kooban oo luqad fudud, taariikhaha iyo waxa lagaa dalbay." },
      { n: "03", t: "Waxaad garanaysaa waxa aad samaynayso", d: "Tallaabooyin cad oo xigta iyo xaddi waqtiga, tartib saxda ah." },
    ],
    who_label: "Ciddee loogu talagalay",
    who_h: "Loogu talagalay dadka ku jira nidaamka.",
    who_sub: "Socdaalayaasha shakhsiga ah, hay'adaha garabka siinaya, iyo qareenada talo siinaya.",
    personas: [
      { t: "Magangalyo doonayaasha", d: "Fahm warqad kasta oo hay'adda socdaalka ka timid iyada oo aan turjumaane loo baahnayn." },
      { t: "Ardayda caalamiga ah", d: "Ha waaysan weligaa cusboonaysiin, ballan, ama xaddi waqti nidaam aan la yaqaan." },
      { t: "Shaqaalaha iyo qoysaska", d: "Dukumantiyadda socdaalka ee guriga ku hay meel keliya." },
    ],
    privacy_label: "Xogta la maareeyo",
    privacy_h: "Dukumantiyadaadu weligood ma tegi prosesyoonka.",
    privacy_sub: "migraDOCS waxa loo naqshadeeyay mabda'a ilaalinta xogta ugu yar ee adag.",
    privacy_points: [
      { t: "Faylka laguma kaydiyo", d: "Dukumantiyadda asalka ah waxaa lagu hawlgalaa xasuusta waxaana la tirtiraa. Kooban habaynta oo keliya ayaa la ilaaliyaa." },
      { t: "Goobaha la soo saaray oo keliya", d: "Taariikhaha, tallaabooyinka loo baahan yahay iyo noocyada — marnaba warqadda asalka ah, marnaba sawirrada bogagga." },
      { t: "Tirtirid la xaqiijin karo", d: "Kooban kasta waxaa si joogto ah looga saari karaa akoonkaaga waqti kasta." },
    ],
    waitlist_h: "Aad u hore u ogaaw.",
    waitlist_sub: "Kaadimaadkaaga ka tag. Waxaan kula xiriiri doonaa markaad isticmaali karto.",
    waitlist_placeholder: "adiga@email.com",
    waitlist_cta: "Ku biir liiska sugitaanka",
    waitlist_joining: "Ku biirnaya…",
    waitlist_ok_t: "Waxaad ku jirtaa liiska.",
    waitlist_ok_d: "Waxaan kula xiriiri doonaa.",
    waitlist_err: "Fadlan geli cinwaanka emaylka oo sax ah.",
    footer_copy: "© 2026 migraDOCS",
    footer_disclaimer: "Macluumaad habayn keliya. Maaha tallo sharci.",
  },
  TI: {
    dir: "ltr",
    nav_cta: "ናብ ዝርዝር ተጸቢ ተጸምበር",
    lang_label: "ቋንቋ",
    hero_kicker: "ዝተወደበ ሓበሬታ · ሕጋዊ ምኽሪ ኣይኮነን",
    hero_h1_1: "ናይ ስደት ስርዓት,",
    hero_h1_2: "ተተርጒሙ።",
    hero_sub: "ሰነድ ጸዓን። እንታይ ትርጉም ከምዘለዎ ተረድኣ። እንታይ ክትገብር ከምዘለካን መዓስን ፍለጥ።",
    hero_cta: "ናብ ዝርዝር ተጸቢ ተጸምበር",
    hero_meta: "ዝኾነ ፋይል ኣይዕቀብን። ይሰርሕ ይሕደግ።",
    doc_plain: "ቀሊል ቋንቋ",
    doc_deadline: "መወዳእታ ዕለት",
    doc_action: "ዘድሊ ስጉምቲ",
    docs: [
      { type: "ምልክታ ፍቓድ", auth: "ቤት ጽሕፈት ስደት", date: "ዝወጸ 12 ሚያዝያ 2026", translation: "ናይ ስራሕ ፍቓድካ ተፈቒዱ ኢዩ። ኣብ ውሽጢ 30 መዓልቲ ብዝምልከተካ ውሰዶ።", deadline: "12 ግንቦት 2026", action: "ቦታ ምቅናይ ሰርሓ" },
      { type: "ደብዳቤ ቆጸራ", auth: "ኣካላዊ ምልክት ኣገልግሎት", date: "ዝወጸ 03 ሚያዝያ 2026", translation: "ኣካላዊ ምልክት ቆጸራ ተዳልዩልካ ኣሎ። ምቅራብ ግዴታ ኢዩ።", deadline: "28 ሚያዝያ 2026", action: "ብዝምልከተካ ቅረብ" },
      { type: "ውሳኔ ይግባኝ", auth: "ቤት ፍርዲ ምምሕዳር", date: "ዝወጸ 21 መጋቢት 2026", translation: "ይግባኝካ ይርኤ ኣሎ። ጽሑፍ ውሳኔ ኣብ ውሽጢ 60 መዓልቲ ክወጽእ ኢዩ።", deadline: "20 ግንቦት 2026", action: "ጽሑፍ ምልክታ ጽበ" },
      { type: "ዝያዳ ሰነዳት", auth: "ቤት ጽሕፈት ስደት", date: "ዝወጸ 08 ሚያዝያ 2026", translation: "ዝያዳ ሰነዳት የድሊ ኢዩ። ዝተዘርዘሩ ሰነዳት ኣብ ውሽጢ 14 መዓልቲ ኣቕርብ፤ ዘይምቕራብካ ናይ ጉዳይካ ናብ ዕረፍቲ ክእቶ ኢዩ።", deadline: "22 ሚያዝያ 2026", action: "3 ሰነዳት ኣቕርብ" },
    ],
    how_label: "ኣሰራርሓ",
    how_h: "ከመይ ጌሩ ይሰርሕ",
    how_sub: "ሰለስተ ስጉምትታት፡ ብዘይ ቴክኒካዊ ቋንቋ።",
    steps: [
      { n: "01", t: "ሰነድካ ጸዓን", d: "ዝኾነ ወግዓዊ ደብዳቤ ወይ ምልክታ ካብ ቤት ጽሕፈት ስደት።" },
      { n: "02", t: "ንሕና ንሰርሖ", d: "ብቐሊል ቋንቋ ጸብጻብ፡ ዕለታትን ናይ ተሓደስካ ሕቶን።" },
      { n: "03", t: "እንታይ ምግባር ከምዘለካ ትፈልጥ", d: "ንጹር ዝቕጽሉ ስጉምትታትን ዕለት ወሰናትን፡ ብሰሳ ተርታ።" },
    ],
    who_label: "ንመን ዝኾነ",
    who_h: "ንሰባት ኣብ ውሽጢ ናይ ሕጊ ስርዓት ዝተሃንጸ።",
    who_sub: "ውልቀ ስደተኛታት፡ ዝድግፍዎም ትካላትን ዝምክሕዎም ጠበቓታትን።",
    personas: [
      { t: "ዑቕባ ሓተቲ", d: "ካብ ቤት ጽሕፈት ምምሕዳር ዝበጽሕ ዝኾነ ደብዳቤ ብዘይ ተርጓሚ ተረድኣ።" },
      { t: "ኣህጉራዊ ተምሃሮ", d: "ኣብ ዘይትፈልጦ ስርዓት ምሕዳስ፡ ቆጸራ ወይ ዕለት-ወሰን ፈጺምካ ኣይትረስዕ።" },
      { t: "ሰራሕተኛታትን ቤተሰብን", d: "ናይ ስደት ሰነዳት ምሉእ ቤተሰብ ኣብ ሓደ ቦታ ኣደራርቦ።" },
    ],
    privacy_label: "ምሕደራ ሓበሬታ",
    privacy_h: "ሰነዳትካ ካብ ናይ ስርሓት ሂደት ፈጺሙ ኣይወጽእን።",
    privacy_sub: "migraDOCS ብናይ ዉሑድ ዕቃበ ሓበሬታ ፖሊሲ ዝቖመ ኢዩ።",
    privacy_points: [
      { t: "ምዕቃብ ፋይል የለን", d: "ናይ ኦርጅናል ሰነዳት ኣብ ዝኽርታ ይሰርሑ ይሕደጉ። ጸብጻብ ዝተወደበ ጥራሕ ይቕምጥ።" },
      { t: "ዝተወጸኡ መስኮታት ጥራሕ", d: "ዕለታት፡ ዘድሊ ስጉምትታት፡ ዓይነታት — ናይ ኦርጅናል ጽሑፍ ፈጺሙ የለን፡ ናይ ገጻት ስእሊ ፈጺሙ የለን።" },
      { t: "ዝርጋን ምርግጋጽ", d: "ዝኾነ ጸብጻብ ካብ ሕሳብካ ንሓሙሽተ ዝኾነ ሰዓት ክጸርግ ይካኣል።" },
    ],
    waitlist_h: "ቅድሚ ኹሉ ፍለጥ።",
    waitlist_sub: "ኢ-መይልካ ሕደጎ። ምስ ኮነ ክንረኽበካ ኢና።",
    waitlist_placeholder: "ንስኻ@email.com",
    waitlist_cta: "ናብ ዝርዝር ተጸቢ ተጸምበር",
    waitlist_joining: "ይጽምበር…",
    waitlist_ok_t: "ኣብ ዝርዝር ኣለኻ።",
    waitlist_ok_d: "ክንረኽበካ ኢና።",
    waitlist_err: "በጃኹም ቅቡል ኣድራሻ ኢ-መይል ኣእቱ።",
    footer_copy: "© 2026 migraDOCS",
    footer_disclaimer: "ዝተወደበ ሓበሬታ ጥራሕ። ሕጋዊ ምኽሪ ኣይኮነን።",
  },
  AM: {
    dir: "ltr",
    nav_cta: "የጥበቃ ዝርዝር ይቀላቀሉ",
    lang_label: "ቋንቋ",
    hero_kicker: "የተደራጀ መረጃ · የህግ ምክር አይደለም",
    hero_h1_1: "የስደት ስርዓት,",
    hero_h1_2: "ተተርጉሟል።",
    hero_sub: "ሰነድ ያስገቡ። ምን ማለት እንደሆነ ይረዱ። ምን ማድረግ እንዳለቦትና መቼ እንደሆነ ይወቁ።",
    hero_cta: "የጥበቃ ዝርዝር ይቀላቀሉ",
    hero_meta: "ምንም ፋይል አይቀመጥም። ይሰራና ይሰረዛል።",
    doc_plain: "ቀላል ቋንቋ",
    doc_deadline: "የመጨረሻ ቀን",
    doc_action: "አስፈላጊ እርምጃ",
    docs: [
      { type: "የፈቃድ ማስታወቂያ", auth: "የስደት ባለስልጣን", date: "የተሰጠው ሚያዝያ 12 ቀን 2026", translation: "የስራ ፈቃድዎ ተፈቅዷል። በ30 ቀናት ውስጥ ራስዎ ይቀበሉ።", deadline: "ግንቦት 12 ቀን 2026", action: "ለመቀበያ ቀጠሮ ይያዙ" },
      { type: "የቀጠሮ ደብዳቤ", auth: "ባዮሜትሪክ አገልግሎቶች", date: "የተሰጠው ሚያዝያ 3 ቀን 2026", translation: "ለባዮሜትሪክ ቀጠሮ ተሰጥዎታል። መገኘት ግዴታ ነው።", deadline: "ሚያዝያ 28 ቀን 2026", action: "ራስዎ ይቅረቡ" },
      { type: "የይግባኝ ውሳኔ", auth: "አስተዳደራዊ ፍርድ ቤት", date: "የተሰጠው መጋቢት 21 ቀን 2026", translation: "ይግባኝዎ እየታየ ነው። በ60 ቀናት ውስጥ የጽሑፍ ውሳኔ ይሰጣል።", deadline: "ግንቦት 20 ቀን 2026", action: "የጽሑፍ ማስታወቂያ ይጠብቁ" },
      { type: "ተጨማሪ ሰነዶች", auth: "የስደት ባለስልጣን", date: "የተሰጠው ሚያዝያ 8 ቀን 2026", translation: "ተጨማሪ ሰነዶች ያስፈልጋሉ። የተዘረዘሩ ሰነዶችን በ14 ቀናት ውስጥ ያስገቡ አለዚያ ጉዳይዎ ይቋረጣል።", deadline: "ሚያዝያ 22 ቀን 2026", action: "3 ሰነዶች ያስገቡ" },
    ],
    how_label: "ሂደት",
    how_h: "እንዴት ይሰራል",
    how_sub: "ሶስት ደረጃዎች፣ ያለ ቴክኒካዊ ቋንቋ።",
    steps: [
      { n: "01", t: "ሰነዱን ያስገቡ", d: "ከስደት ባለስልጣን የሚመጣ ማንኛውም ኦፊሴላዊ ደብዳቤ ወይም ማስታወቂያ።" },
      { n: "02", t: "እናብራራለን", d: "በቀላል ቋንቋ ማጠቃለያ፣ ቀናቶች እና ምን እንደሚፈለግ።" },
      { n: "03", t: "ምን ማድረግ እንዳለቦት ያውቃሉ", d: "ግልጽ ቀጣይ እርምጃዎች እና የመጨረሻ ቀናቶች፣ በትክክለኛ ቅደም ተከተል።" },
    ],
    who_label: "ለማን",
    who_h: "ለስርዓቱ ውስጥ ላሉ ሰዎች ተሰርቷል።",
    who_sub: "ግለሰብ ስደተኞች፣ የሚደግፉ ድርጅቶች፣ እና የሚመክሩ ጠበቃዎች።",
    personas: [
      { t: "የጥገኝነት ጠያቂዎች", d: "ከስደት ባለስልጣን የሚመጡ ደብዳቤዎችን ሁሉ ያለ ተርጓሚ ይረዱ።" },
      { t: "ዓለም አቀፍ ተማሪዎች", d: "ምንጊዜም የታደሰ ፈቃድ፣ ቀጠሮ ወይም የመጨረሻ ቀን አያጡ።" },
      { t: "ሰራተኞች እና ቤተሰቦች", d: "የቤተሰቡ የስደት ሰነዶችን ሁሉ በአንድ ቦታ ያደራጁ።" },
    ],
    privacy_label: "የውሂብ አስተዳደር",
    privacy_h: "ሰነዶችዎ ከሂደቱ አይወጡም።",
    privacy_sub: "migraDOCS ዝቅተኛ የውሂብ ማቆያ መርህ ላይ ተመስርቶ ተሰርቷል።",
    privacy_points: [
      { t: "ፋይሎች አይቀመጡም", d: "ዋናዎቹ ሰነዶች በትዝታ ውስጥ ይሰራሉ እና ይሰረዛሉ። የተደራጀ ማጠቃለያ ብቻ ይቀምጣል።" },
      { t: "የተወጡ ሜዳዎች ብቻ", d: "ቀናቶች፣ አስፈላጊ እርምጃዎች እና ምድቦች — ዋናውን ደብዳቤ አይደለም፣ የገጽ ፎቶዎች አይደሉም።" },
      { t: "ሊረጋገጥ የሚችል ስረዛ", d: "ማንኛውም ማጠቃለያ ከሂሳብዎ በማንኛውም ጊዜ ቋሚ በሆነ መልኩ ሊሰረዝ ይችላል።" },
    ],
    waitlist_h: "ቀድመው ይወቁ።",
    waitlist_sub: "ኢሜልዎን ይተዉ። ሲዘጋጅ እናገኝዎታለን።",
    waitlist_placeholder: "እርስዎ@email.com",
    waitlist_cta: "የጥበቃ ዝርዝር ይቀላቀሉ",
    waitlist_joining: "እየተቀላቀሉ…",
    waitlist_ok_t: "በዝርዝሩ ላይ ናቸው።",
    waitlist_ok_d: "እናገኝዎታለን።",
    waitlist_err: "እባክዎ ትክክለኛ የኢሜይል አድራሻ ያስገቡ።",
    footer_copy: "© 2026 migraDOCS",
    footer_disclaimer: "የተደራጀ መረጃ ብቻ። የህግ ምክር አይደለም።",
  },
  SW: {
    dir: "ltr",
    nav_cta: "Jiunge na orodha ya kusubiri",
    lang_label: "Lugha",
    hero_kicker: "HABARI ILIYOPANGWA · SI USHAURI WA KISHERIA",
    hero_h1_1: "Mfumo wa uhamiaji,",
    hero_h1_2: "uliotafsiriwa.",
    hero_sub: "Pakia hati. Elewa inamaanisha nini. Jua nini cha kufanya na lini.",
    hero_cta: "Jiunge na orodha ya kusubiri",
    hero_meta: "Hakuna faili inayohifadhiwa. Inashughulikiwa na kutupwa.",
    doc_plain: "Lugha rahisi",
    doc_deadline: "Tarehe ya mwisho",
    doc_action: "Hatua inayohitajika",
    docs: [
      { type: "Notisi ya kibali", auth: "Mamlaka ya Uhamiaji", date: "Ilitolewa 12 Aprili 2026", translation: "Kibali chako cha kazi kimeidhinishwa. Kichukue wewe mwenyewe ndani ya siku 30.", deadline: "12 Mei 2026", action: "Panga miadi ya kukichukua" },
      { type: "Barua ya miadi", auth: "Huduma za Biometri", date: "Ilitolewa 03 Aprili 2026", translation: "Umepangwa miadi ya biometri. Kuhudhuria ni lazima.", deadline: "28 Aprili 2026", action: "Hudhuria wewe mwenyewe" },
      { type: "Uamuzi wa rufaa", auth: "Mahakama ya Utawala", date: "Ilitolewa 21 Machi 2026", translation: "Rufaa yako inakaguliwa. Uamuzi wa maandishi utatoka ndani ya siku 60.", deadline: "20 Mei 2026", action: "Subiri taarifa ya maandishi" },
      { type: "Nyaraka za ziada", auth: "Mamlaka ya Uhamiaji", date: "Ilitolewa 08 Aprili 2026", translation: "Nyaraka za ziada zinahitajika. Wasilisha vipande vilivyoorodheshwa ndani ya siku 14 au kesi yako itasimamishwa.", deadline: "22 Aprili 2026", action: "Wasilisha nyaraka 3" },
    ],
    how_label: "Mchakato",
    how_h: "Jinsi inavyofanya kazi",
    how_sub: "Hatua tatu, bila istilahi.",
    steps: [
      { n: "01", t: "Pakia hati yako", d: "Barua yoyote rasmi au taarifa kutoka kwa mamlaka ya uhamiaji." },
      { n: "02", t: "Tunaeleza", d: "Muhtasari kwa lugha rahisi, tarehe na kinachohitajika kwako." },
      { n: "03", t: "Unajua nini cha kufanya", d: "Hatua za wazi za baadaye na tarehe za mwisho, kwa mpangilio sahihi." },
    ],
    who_label: "Kwa nani",
    who_h: "Imejengwa kwa watu ndani ya mfumo.",
    who_sub: "Wahamiaji binafsi, NGO zinazowaunga mkono, na mawakili wanaowashauri.",
    personas: [
      { t: "Waombaji wa hifadhi", d: "Elewa kila barua kutoka kwa mamlaka bila kuhitaji mtafsiri." },
      { t: "Wanafunzi wa kimataifa", d: "Usikose kamwe upya, miadi au tarehe ya mwisho katika mfumo usiojua." },
      { t: "Wafanyakazi na familia", d: "Weka hati za uhamiaji za nyumba zote zikipangwa mahali pamoja." },
    ],
    privacy_label: "Usimamizi wa data",
    privacy_h: "Hati zako hazitoki kamwe kwenye usindikaji.",
    privacy_sub: "migraDOCS imeundwa kuzunguka kanuni kali ya uhifadhi mdogo.",
    privacy_points: [
      { t: "Hakuna uhifadhi wa faili", d: "Hati za asili zinashughulikiwa kwenye kumbukumbu na kutupwa. Muhtasari tu uliodhibitiwa huhifadhiwa." },
      { t: "Sehemu zilizotolewa tu", d: "Tarehe, vitendo vinavyohitajika na makundi — kamwe barua ghafi, kamwe picha za kurasa." },
      { t: "Ufutaji unaoweza kukaguliwa", d: "Kila muhtasari unaweza kufutwa kabisa kutoka kwa akaunti yako wakati wowote." },
    ],
    waitlist_h: "Kuwa wa kwanza kujua.",
    waitlist_sub: "Acha barua pepe yako. Tutawasiliana nawe inapokuwa tayari.",
    waitlist_placeholder: "wewe@email.com",
    waitlist_cta: "Jiunge na orodha ya kusubiri",
    waitlist_joining: "Inajiunga…",
    waitlist_ok_t: "Uko kwenye orodha.",
    waitlist_ok_d: "Tutawasiliana nawe.",
    waitlist_err: "Tafadhali ingiza anwani ya barua pepe halali.",
    footer_copy: "© 2026 migraDOCS",
    footer_disclaimer: "Habari iliyopangwa tu. Si ushauri wa kisheria.",
  },
  HA: {
    dir: "ltr",
    nav_cta: "Shiga jerin jira",
    lang_label: "Harshe",
    hero_kicker: "BAYANI TSARI · BA SHAWARA TA SHARI'A BA",
    hero_h1_1: "Tsarin ƙaura,",
    hero_h1_2: "an fassara.",
    hero_sub: "Ɗora takarda. Fahimci abin da take nufi. San abin da za a yi da kuma lokacin.",
    hero_cta: "Shiga jerin jira",
    hero_meta: "Ba a adana kowane fayil. An sarrafa kuma an share.",
    doc_plain: "Sauƙin harshe",
    doc_deadline: "Ƙarshen lokaci",
    doc_action: "Mataki da ake bukata",
    docs: [
      { type: "Sanarwar izini", auth: "Hukumar Ƙaura", date: "An bayar a 12 Afrilu 2026", translation: "An amince da izinin aikinku. Karɓi shi da kanka cikin kwana 30.", deadline: "12 Mayu 2026", action: "Yi alƙawarin karɓa" },
      { type: "Wasiƙar alƙawari", auth: "Sabis na Bayometric", date: "An bayar a 03 Afrilu 2026", translation: "An shirya alƙawarin bayometric a gare ku. Halarta wajibi ne.", deadline: "28 Afrilu 2026", action: "Zo da kanka" },
      { type: "Hukuncin ƙara", auth: "Kotun Gudanarwa", date: "An bayar a 21 Maris 2026", translation: "Ana duba ƙarar ku. Za a bayar da hukunci a rubuce cikin kwana 60.", deadline: "20 Mayu 2026", action: "Jira sanarwa a rubuce" },
      { type: "Karin takardu", auth: "Hukumar Ƙaura", date: "An bayar a 08 Afrilu 2026", translation: "Ana buƙatar ƙarin takardu. Mika abubuwan da aka lissafa cikin kwana 14 ko za a dakatar da ƙarar ku.", deadline: "22 Afrilu 2026", action: "Mika takardu 3" },
    ],
    how_label: "Tsari",
    how_h: "Yadda yake aiki",
    how_sub: "Mataki uku, ba tare da fasaha ba.",
    steps: [
      { n: "01", t: "Ɗora takardarka", d: "Kowane wasiƙa ko sanarwa ta hukuma daga hukumar ƙaura." },
      { n: "02", t: "Muna bayanin", d: "Taƙaitawa da sauƙin harshe, kwanakin da abin da ake buƙata daga gare ku." },
      { n: "03", t: "Kun san abin da za a yi", d: "Matakan gaba da ke a bayyane da ƙarshen lokaci, a tsari daidai." },
    ],
    who_label: "Don waye",
    who_h: "An gina don mutanen da ke cikin tsarin.",
    who_sub: "Baƙi ɗaya ɗaya, ƙungiyoyin da ke taimakonsu, da lauyoyin da ke ba su shawara.",
    personas: [
      { t: "Masu neman mafaka", d: "Fahimci kowane wasiƙa daga hukuma ba tare da mai fassara ba." },
      { t: "Ɗalibai na duniya", d: "Kada ku taɓa rasa sabuntawa, alƙawari ko ƙarshen lokaci a tsari da ba a saba ba." },
      { t: "Ma'aikata da iyalai", d: "Ajiye takardu na ƙaura na gida ɗaya a wuri guda." },
    ],
    privacy_label: "Sarrafa bayanai",
    privacy_h: "Takardunku ba su taɓa barin sarrafawa ba.",
    privacy_sub: "An gina migraDOCS a kusa da ƙa'idar adana bayanai mafi ƙaranci.",
    privacy_points: [
      { t: "Ba a adana fayil", d: "Ana sarrafa takardu na asali a cikin ƙwaƙwalwa sannan a zubar. Ana riƙe da taƙaitawa tsari ne kawai." },
      { t: "Filayen da aka samo kawai", d: "Kwanakin, matakan da ake buƙata da nau'o'i — ba wasiƙar asali ba, ba hotunan shafuka ba." },
      { t: "Share da za a iya tabbatarwa", d: "Za a iya share kowane taƙaitawa daga asusunka har abada a kowane lokaci." },
    ],
    waitlist_h: "Kasance na farko da ya sani.",
    waitlist_sub: "Bar imel ɗinka. Za mu tuntuɓe ka.",
    waitlist_placeholder: "kai@email.com",
    waitlist_cta: "Shiga jerin jira",
    waitlist_joining: "Shiga…",
    waitlist_ok_t: "Kana cikin jerin.",
    waitlist_ok_d: "Za mu tuntuɓe ka.",
    waitlist_err: "Da fatan za a shigar da adireshin imel mai inganci.",
    footer_copy: "© 2026 migraDOCS",
    footer_disclaimer: "Bayani tsari kawai. Ba shawara ta shari'a ba.",
  },
  AR: {
    dir: "rtl",
    nav_cta: "الانضمام إلى قائمة الانتظار",
    lang_label: "اللغة",
    hero_kicker: "معلومات منظَّمة · ليست استشارة قانونية",
    hero_h1_1: "نظام الهجرة،",
    hero_h1_2: "مُترجَمًا.",
    hero_sub: "ارفع المستند. افهم مضمونه. اعرف ما يجب فعله ومتى.",
    hero_cta: "الانضمام إلى قائمة الانتظار",
    hero_meta: "لا يُخزَّن أي ملف. يُعالَج ثم يُتلَف.",
    doc_plain: "لغة مبسّطة",
    doc_deadline: "الموعد النهائي",
    doc_action: "الإجراء المطلوب",
    docs: [
      { type: "إشعار تصريح", auth: "سلطة الهجرة", date: "صدر في ١٢ أبريل ٢٠٢٦", translation: "تمت الموافقة على تصريح عملك. استلمه شخصيًا خلال ٣٠ يومًا.", deadline: "١٢ مايو ٢٠٢٦", action: "حجز موعد الاستلام" },
      { type: "رسالة موعد", auth: "القياسات الحيوية", date: "صدر في ٣ أبريل ٢٠٢٦", translation: "تم تحديد موعد لقياساتك الحيوية. الحضور إلزامي.", deadline: "٢٨ أبريل ٢٠٢٦", action: "الحضور شخصيًا" },
      { type: "قرار استئناف", auth: "المحكمة الإدارية", date: "صدر في ٢١ مارس ٢٠٢٦", translation: "استئنافك قيد المراجعة. سيصدر قرار كتابي خلال ٦٠ يومًا.", deadline: "٢٠ مايو ٢٠٢٦", action: "انتظار الإشعار الكتابي" },
      { type: "طلب مستندات", auth: "سلطة الهجرة", date: "صدر في ٨ أبريل ٢٠٢٦", translation: "مطلوب مستندات إضافية. قدّمها خلال ١٤ يومًا وإلا عُلّقت قضيتك.", deadline: "٢٢ أبريل ٢٠٢٦", action: "تقديم ٣ مستندات" },
    ],
    how_label: "العملية",
    how_h: "كيف تعمل",
    how_sub: "ثلاث خطوات، دون تعقيد.",
    steps: [
      { n: "٠١", t: "ارفع مستندك", d: "أي رسالة رسمية أو إشعار من سلطة الهجرة." },
      { n: "٠٢", t: "نشرحه لك", d: "ملخّص بلغة واضحة، وتواريخ، وما هو مطلوب منك." },
      { n: "٠٣", t: "تعرف ما تفعل", d: "خطوات تالية واضحة ومواعيد، بالترتيب الصحيح." },
    ],
    who_label: "لمن",
    who_h: "مُصمَّم لمن هم داخل النظام.",
    who_sub: "المهاجرون الأفراد، المنظمات التي تدعمهم، والمحامون الذين يستشيرونهم.",
    personas: [
      { t: "طالبو اللجوء", d: "افهم كل رسالة من سلطة الهجرة دون الحاجة إلى مترجم." },
      { t: "الطلاب الدوليون", d: "لا تفوّت تجديدًا أو موعدًا أو موعدًا نهائيًا في نظام غير مألوف." },
      { t: "العاملون والعائلات", d: "احفظ مستندات هجرة الأسرة كاملة في مكان واحد." },
    ],
    privacy_label: "معالجة البيانات",
    privacy_h: "مستنداتك لا تغادر مرحلة المعالجة.",
    privacy_sub: "migraDOCS مبني حول مبدأ صارم لأقل قدر من الاحتفاظ بالبيانات.",
    privacy_points: [
      { t: "لا تخزين للملفات", d: "تُعالَج المستندات الأصلية في الذاكرة ثم تُتلَف. يُحتفظ فقط بالملخّص المنظَّم." },
      { t: "حقول مستخرجة فقط", d: "تواريخ وإجراءات وتصنيفات — ولا شيء من النص الأصلي أو صور الصفحات." },
      { t: "حذف قابل للتدقيق", d: "يمكن محو أي ملخّص نهائيًا من حسابك في أي وقت." },
    ],
    waitlist_h: "كن أول من يعرف.",
    waitlist_sub: "اترك بريدك الإلكتروني. سنتواصل معك عند إتاحة الخدمة.",
    waitlist_placeholder: "you@email.com",
    waitlist_cta: "الانضمام إلى قائمة الانتظار",
    waitlist_joining: "جاري الإضافة…",
    waitlist_ok_t: "أنت على القائمة.",
    waitlist_ok_d: "سنتواصل معك.",
    waitlist_err: "يرجى إدخال بريد إلكتروني صالح.",
    footer_copy: "© ٢٠٢٦ migraDOCS",
    footer_disclaimer: "معلومات منظَّمة فقط. ليست استشارة قانونية.",
  },
  ZH: {
    dir: "ltr",
    nav_cta: "加入等候名单",
    lang_label: "语言",
    hero_kicker: "结构化信息 · 非法律建议",
    hero_h1_1: "移民系统，",
    hero_h1_2: "看懂它。",
    hero_sub: "上传文件，读懂内容，知道该做什么、何时去做。",
    hero_cta: "加入等候名单",
    hero_meta: "文件不会被保存，处理后立即删除。",
    doc_plain: "通俗解释",
    doc_deadline: "截止日期",
    doc_action: "所需行动",
    docs: [
      { type: "工作许可通知", auth: "移民局", date: "2026年4月12日签发", translation: "您的工作许可已获批准，请在30天内亲自前往领取。", deadline: "2026年5月12日", action: "预约领取" },
      { type: "生物特征预约函", auth: "生物特征采集中心", date: "2026年4月3日签发", translation: "您的生物特征采集预约已确认，必须本人出席。", deadline: "2026年4月28日", action: "本人到场" },
      { type: "上诉裁定通知", auth: "行政法院", date: "2026年3月21日签发", translation: "您的上诉正在审查中，书面裁定将在60天内发出。", deadline: "2026年5月20日", action: "等待书面通知" },
      { type: "补交材料通知", auth: "移民局", date: "2026年4月8日签发", translation: "需要补交额外材料，请在14天内提交，否则案件将被暂停处理。", deadline: "2026年4月22日", action: "提交3份文件" },
    ],
    how_label: "流程",
    how_h: "使用方式",
    how_sub: "三个步骤，简单明了。",
    steps: [
      { n: "01", t: "上传文件", d: "任何来自移民部门的官方信件或通知。" },
      { n: "02", t: "读懂内容", d: "获得通俗摘要、关键日期及所需行动。" },
      { n: "03", t: "知道下一步", d: "按正确顺序列出清晰的后续步骤与截止时间。" },
    ],
    who_label: "适用人群",
    who_h: "为身处移民系统中的人而设。",
    who_sub: "个人移民者、支持他们的机构，以及为他们提供咨询的律师。",
    personas: [
      { t: "庇护申请人", d: "无需翻译，即可理解移民局每一封来信。" },
      { t: "国际学生", d: "不错过陌生系统中的任何续签、预约或截止日期。" },
      { t: "工作者与家庭", d: "将全家的移民文件集中保存在一处。" },
    ],
    privacy_label: "数据处理",
    privacy_h: "您的文件不会离开处理环节。",
    privacy_sub: "migraDOCS 遵循严格的最小数据保留原则。",
    privacy_points: [
      { t: "不存储文件", d: "原始文件在内存中处理后立即销毁，仅保留结构化摘要。" },
      { t: "仅提取字段", d: "只保存日期、操作和分类，不保留原文内容或页面图像。" },
      { t: "可审计删除", d: "您可随时从账户中永久删除任何摘要。" },
    ],
    waitlist_h: "率先获得通知。",
    waitlist_sub: "留下您的邮箱，我们将在服务上线时联系您。",
    waitlist_placeholder: "you@email.com",
    waitlist_cta: "加入等候名单",
    waitlist_joining: "提交中…",
    waitlist_ok_t: "您已加入名单。",
    waitlist_ok_d: "我们会与您联系。",
    waitlist_err: "请输入有效的电子邮件地址。",
    footer_copy: "© 2026 migraDOCS",
    footer_disclaimer: "仅提供结构化信息，非法律建议。",
  },
};
