import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — migraDOCS",
  description: "Terms and conditions for using migraDOCS.",
};

const LAST_UPDATED = "2026-04-19";
const CONTACT_EMAIL = "legal@migradocs.org";
const COMPANY_NAME = "migraDOCS";
// TODO: Replace with registered company name and address before going live
const COMPANY_ADDRESS = "[Company name and registered address]";

export default function TermsPage() {
  return (
    <div style={{ fontFamily: "Inter, sans-serif", color: "var(--ink, #0d1855)", background: "#fff", minHeight: "100vh" }}>
      {/* Nav */}
      <header style={{ borderBottom: "1px solid #dce4f8", padding: "0 24px", height: 56, display: "flex", alignItems: "center", justifyContent: "space-between" }}>
        <Link href="/" style={{ textDecoration: "none", fontWeight: 700, fontSize: 16, color: "var(--navy, #1c2e9e)" }}>
          migraDOCS
        </Link>
        <Link href="/privacy" style={{ fontSize: 13, color: "#5d6b9a", textDecoration: "none" }}>
          Privacy Policy →
        </Link>
      </header>

      {/* Content */}
      <main style={{ maxWidth: 720, margin: "0 auto", padding: "48px 24px 80px" }}>
        <h1 style={{ fontSize: 28, fontWeight: 700, marginBottom: 8 }}>Terms of Service</h1>
        <p style={{ fontSize: 13, color: "#8a99c5", marginBottom: 40 }}>Last updated: {LAST_UPDATED}</p>

        <Section title="1. About the service">
          <p>
            {COMPANY_NAME} is operated by {COMPANY_ADDRESS} ("{COMPANY_NAME}", "we", "us"). We provide
            a tool that helps users understand immigration documents, identify relevant immigration
            processes, and track the steps involved in those processes.
          </p>
          <p>
            By using {COMPANY_NAME} you agree to these Terms. If you do not agree, do not use the service.
          </p>
        </Section>

        <Section title="2. Not legal advice — important disclaimer">
          <div style={{ background: "#fff8e1", border: "1px solid #f59e0b", borderRadius: 8, padding: "16px 20px", marginBottom: 16 }}>
            <strong>migraDOCS does not provide legal advice.</strong>
          </div>
          <p>
            The information, process plans, and guidance provided by {COMPANY_NAME} — whether generated
            by AI or from pre-built templates — is <strong>general information only</strong>. It is not
            legal advice, immigration advice, or a substitute for advice from a qualified immigration
            lawyer or regulated immigration adviser.
          </p>
          <p>
            Immigration rules change frequently. Information on this platform may not reflect the most
            recent rules, fees, or requirements. <strong>Always verify requirements directly with the
            relevant authority before submitting any application.</strong>
          </p>
          <p>
            We expressly disclaim all liability for any loss, harm, or adverse immigration outcome
            arising from reliance on information provided by this service.
          </p>
        </Section>

        <Section title="3. Eligibility">
          <p>
            You must be at least <strong>18 years old</strong> to use {COMPANY_NAME}. By creating an
            account you confirm that you are 18 or over. We do not knowingly provide services to
            persons under 18.
          </p>
        </Section>

        <Section title="4. Your account">
          <p>
            You are responsible for maintaining the security of your account credentials. You are
            responsible for all activity that occurs under your account. Notify us immediately at{" "}
            <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> if you suspect unauthorised access.
          </p>
        </Section>

        <Section title="5. Acceptable use">
          <p>You agree not to:</p>
          <ul>
            <li>Use the service to assist in circumventing, evading, or violating immigration law</li>
            <li>Submit false or misleading information</li>
            <li>Use the service on behalf of others for commercial gain without our written permission</li>
            <li>Attempt to scrape, reverse-engineer, or extract the underlying data or models</li>
            <li>Upload documents belonging to others without their explicit consent</li>
            <li>Use the service in any way that could cause harm to vulnerable persons</li>
          </ul>
        </Section>

        <Section title="6. AI-generated content">
          <p>
            Some guidance on this platform is generated by artificial intelligence (Anthropic's Claude).
            AI-generated content:
          </p>
          <ul>
            <li>May contain errors, omissions, or outdated information</li>
            <li>Is not reviewed by a qualified immigration adviser before being shown to you</li>
            <li>Should not be relied upon as your sole source of information for any immigration decision</li>
          </ul>
          <p>
            Where possible we use pre-built, human-reviewed process templates. When AI is used, an
            uncertainty notice is displayed alongside the generated content.
          </p>
        </Section>

        <Section title="7. Your data and documents">
          <p>
            You retain ownership of any documents you upload. Document files are stored in your own
            Google Drive account and are not accessed by us except as necessary to provide the service.
            See our <Link href="/privacy">Privacy Policy</Link> for full details.
          </p>
        </Section>

        <Section title="8. Limitation of liability">
          <p>
            To the maximum extent permitted by applicable law, {COMPANY_NAME} and its operators shall
            not be liable for any indirect, incidental, special, consequential, or punitive damages,
            including but not limited to: loss of immigration status, missed application deadlines,
            refused applications, legal costs, or any other loss arising from use of or reliance on
            this service.
          </p>
          <p>
            Our total liability to you for any claim arising out of these Terms or use of the service
            shall not exceed the amount you have paid to us in the 12 months preceding the claim.
          </p>
        </Section>

        <Section title="9. Availability">
          <p>
            We do not guarantee that the service will be available at all times. We may modify,
            suspend, or discontinue the service at any time with reasonable notice where possible.
          </p>
        </Section>

        <Section title="10. Governing law">
          <p>
            These Terms are governed by the laws of Sweden. Any disputes shall be subject to the
            exclusive jurisdiction of the Swedish courts.
            {/* TODO: Confirm jurisdiction with a lawyer — may need adjusting depending on company registration */}
          </p>
        </Section>

        <Section title="11. Changes to these Terms">
          <p>
            We may update these Terms from time to time. We will notify you of material changes by
            email at least 14 days before they take effect. Continued use of the service after changes
            take effect constitutes acceptance.
          </p>
        </Section>

        <Section title="12. Contact">
          <p>
            {COMPANY_NAME}<br />
            {COMPANY_ADDRESS}<br />
            <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>
          </p>
        </Section>
      </main>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 36 }}>
      <h2 style={{ fontSize: 17, fontWeight: 700, marginBottom: 12, color: "#1c2e9e" }}>{title}</h2>
      <div style={{ fontSize: 15, lineHeight: 1.7, color: "#283882" }}>
        {children}
      </div>
    </section>
  );
}
